import { NeonatalAlert, HistoryEntry } from "./types";

const minsAgo = (m: number): string =>
  new Date(Date.now() - m * 60_000).toISOString();

/** 1 RED, 2 YELLOW, 7 GREEN = 10 patients */
export const MOCK_ALERTS: NeonatalAlert[] = [
  {
    patient_id: "infant1",
    timestamp: minsAgo(3),
    concern_level: "RED",
    risk_score: 0.84,
    primary_indicators: ["rmssd", "lf_hf_ratio", "pnn50"],
    clinical_reasoning:
      "Marked suppression of RMSSD (z=-3.2) and pNN50 (z=-2.9) combined with elevated LF/HF ratio (z=+2.8) is consistent with autonomic withdrawal preceding neonatal sepsis. Three bradycardia events in the last 6 hours reinforce the pre-sepsis HRV signature. Risk score 0.84 exceeds the RED threshold.",
    recommended_action: "Immediate clinical review",
    confidence: 0.91,
    retrieved_context: [],
    self_check_passed: true,
    protocol_compliant: true,
    past_similar_events: 2,
    latency_ms: 420,
    z_scores: {
      rmssd: -3.2,
      lf_hf_ratio: 2.8,
      pnn50: -2.9,
      sdnn: -2.1,
      mean_rr: -1.4,
    },
  },
  {
    patient_id: "infant2",
    timestamp: minsAgo(7),
    concern_level: "YELLOW",
    risk_score: 0.58,
    primary_indicators: ["lf_hf_ratio", "rmssd"],
    clinical_reasoning:
      "Moderate LF/HF elevation (z=+2.1) with mild RMSSD suppression (z=-1.6). Pattern is indeterminate — consistent with either early autonomic stress or normal sleep-state variation in a preterm neonate. No bradycardia events in the last 6 hours.",
    recommended_action: "Reassess in 2 hours",
    confidence: 0.72,
    retrieved_context: [],
    self_check_passed: true,
    protocol_compliant: true,
    past_similar_events: 1,
    latency_ms: 388,
    z_scores: {
      lf_hf_ratio: 2.1,
      rmssd: -1.6,
      sdnn: -0.8,
      pnn50: -0.6,
      mean_rr: 0.3,
    },
  },
  {
    patient_id: "infant3",
    timestamp: minsAgo(12),
    concern_level: "YELLOW",
    risk_score: 0.47,
    primary_indicators: ["sdnn", "rmssd"],
    clinical_reasoning:
      "SDNN mildly reduced (z=-1.4) alongside borderline RMSSD suppression (z=-1.2). Isolated finding with no bradycardia. Consistent with feed-related HRV suppression but warrants monitoring given gestational age.",
    recommended_action: "Increase monitoring frequency to every 15 minutes",
    confidence: 0.68,
    retrieved_context: [],
    self_check_passed: true,
    protocol_compliant: true,
    past_similar_events: 0,
    latency_ms: 301,
    z_scores: {
      sdnn: -1.4,
      rmssd: -1.2,
      lf_hf_ratio: 0.4,
      pnn50: -0.9,
      mean_rr: 0.1,
    },
  },
  {
    patient_id: "infant4",
    timestamp: minsAgo(4),
    concern_level: "GREEN",
    risk_score: 0.18,
    primary_indicators: ["rmssd"],
    clinical_reasoning:
      "All HRV parameters within normal variation range for this patient's baseline. RMSSD z-score -0.3. No bradycardia events.",
    recommended_action: "Continue routine monitoring",
    confidence: 0.91,
    retrieved_context: [],
    self_check_passed: true,
    protocol_compliant: true,
    past_similar_events: 0,
    latency_ms: 290,
    z_scores: {
      rmssd: -0.3,
      sdnn: 0.4,
      lf_hf_ratio: 0.2,
      pnn50: -0.1,
      mean_rr: 0.0,
    },
  },
  {
    patient_id: "infant5",
    timestamp: minsAgo(6),
    concern_level: "GREEN",
    risk_score: 0.12,
    primary_indicators: ["sdnn"],
    clinical_reasoning:
      "Stable HRV profile. SDNN within personal baseline range (z=+0.4). No events.",
    recommended_action: "Continue routine monitoring",
    confidence: 0.93,
    retrieved_context: [],
    self_check_passed: true,
    protocol_compliant: true,
    past_similar_events: 0,
    latency_ms: 275,
    z_scores: {
      sdnn: 0.4,
      rmssd: 0.1,
      lf_hf_ratio: 0.1,
      pnn50: 0.0,
      mean_rr: 0.2,
    },
  },
  {
    patient_id: "infant6",
    timestamp: minsAgo(9),
    concern_level: "GREEN",
    risk_score: 0.22,
    primary_indicators: ["lf_hf_ratio"],
    clinical_reasoning:
      "Mild LF/HF elevation (z=+0.9) within normal variation. No autonomic withdrawal pattern. No bradycardia.",
    recommended_action: "Continue routine monitoring",
    confidence: 0.88,
    retrieved_context: [],
    self_check_passed: true,
    protocol_compliant: true,
    past_similar_events: 0,
    latency_ms: 310,
    z_scores: {
      lf_hf_ratio: 0.9,
      rmssd: 0.1,
      sdnn: 0.3,
      pnn50: 0.1,
      mean_rr: 0.0,
    },
  },
  {
    patient_id: "infant7",
    timestamp: minsAgo(2),
    concern_level: "GREEN",
    risk_score: 0.09,
    primary_indicators: ["rmssd"],
    clinical_reasoning:
      "All indicators stable. HRV consistent with normal sleep-cycle variation.",
    recommended_action: "Continue routine monitoring",
    confidence: 0.95,
    retrieved_context: [],
    self_check_passed: true,
    protocol_compliant: true,
    past_similar_events: 0,
    latency_ms: 265,
    z_scores: {
      rmssd: -0.2,
      sdnn: 0.1,
      lf_hf_ratio: 0.1,
      pnn50: 0.0,
      mean_rr: 0.1,
    },
  },
  {
    patient_id: "infant8",
    timestamp: minsAgo(14),
    concern_level: "GREEN",
    risk_score: 0.31,
    primary_indicators: ["pnn50"],
    clinical_reasoning:
      "pNN50 slightly below baseline (z=-0.8). No clinical significance at this level. Risk score 0.31 within GREEN range.",
    recommended_action: "Continue routine monitoring",
    confidence: 0.87,
    retrieved_context: [],
    self_check_passed: true,
    protocol_compliant: true,
    past_similar_events: 0,
    latency_ms: 298,
    z_scores: {
      pnn50: -0.8,
      rmssd: -0.2,
      sdnn: 0.1,
      lf_hf_ratio: 0.2,
      mean_rr: 0.0,
    },
  },
  {
    patient_id: "infant9",
    timestamp: minsAgo(5),
    concern_level: "GREEN",
    risk_score: 0.15,
    primary_indicators: ["sdnn"],
    clinical_reasoning:
      "SDNN within expected range. No deviations of clinical concern. Stable baseline.",
    recommended_action: "Continue routine monitoring",
    confidence: 0.92,
    retrieved_context: [],
    self_check_passed: true,
    protocol_compliant: true,
    past_similar_events: 0,
    latency_ms: 280,
    z_scores: {
      sdnn: 0.2,
      rmssd: 0.1,
      lf_hf_ratio: 0.0,
      pnn50: 0.1,
      mean_rr: 0.1,
    },
  },
  {
    patient_id: "infant10",
    timestamp: minsAgo(8),
    concern_level: "GREEN",
    risk_score: 0.26,
    primary_indicators: ["rmssd"],
    clinical_reasoning:
      "Mild RMSSD variation (z=-0.7) within normal range. No bradycardia. Stable post-feed profile.",
    recommended_action: "Continue routine monitoring",
    confidence: 0.89,
    retrieved_context: [],
    self_check_passed: true,
    protocol_compliant: true,
    past_similar_events: 0,
    latency_ms: 305,
    z_scores: {
      rmssd: -0.7,
      sdnn: 0.2,
      lf_hf_ratio: 0.1,
      pnn50: -0.2,
      mean_rr: 0.0,
    },
  },
];

/** At least one history row per bed so every drawer can show a timeline in mock mode. */
export const MOCK_HISTORY: Record<string, HistoryEntry[]> = {
  infant1: [
    {
      timestamp: minsAgo(93),
      concern_level: "RED",
      risk_score: 0.81,
      top_feature: "rmssd",
      top_z_score: -3.1,
      signal_pattern: "pre_sepsis",
      brady_classification: "recurrent_without_suppression",
      agent_version: "multi_agent",
    },
    {
      timestamp: minsAgo(183),
      concern_level: "YELLOW",
      risk_score: 0.52,
      top_feature: "lf_hf_ratio",
      top_z_score: 2.2,
      signal_pattern: "indeterminate",
      brady_classification: null,
      agent_version: "multi_agent",
    },
    {
      timestamp: minsAgo(273),
      concern_level: "GREEN",
      risk_score: 0.21,
      top_feature: "rmssd",
      top_z_score: -0.8,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
  ],
  infant2: [
    {
      timestamp: minsAgo(97),
      concern_level: "YELLOW",
      risk_score: 0.55,
      top_feature: "lf_hf_ratio",
      top_z_score: 1.9,
      signal_pattern: "indeterminate",
      brady_classification: null,
      agent_version: "multi_agent",
    },
    {
      timestamp: minsAgo(187),
      concern_level: "GREEN",
      risk_score: 0.28,
      top_feature: "rmssd",
      top_z_score: -0.6,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
  ],
  infant3: [
    {
      timestamp: minsAgo(88),
      concern_level: "GREEN",
      risk_score: 0.32,
      top_feature: "sdnn",
      top_z_score: -0.9,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
    {
      timestamp: minsAgo(178),
      concern_level: "GREEN",
      risk_score: 0.26,
      top_feature: "rmssd",
      top_z_score: -0.5,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
  ],
  infant4: [
    {
      timestamp: minsAgo(105),
      concern_level: "GREEN",
      risk_score: 0.2,
      top_feature: "rmssd",
      top_z_score: -0.35,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
    {
      timestamp: minsAgo(220),
      concern_level: "GREEN",
      risk_score: 0.17,
      top_feature: "sdnn",
      top_z_score: 0.2,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
  ],
  infant5: [
    {
      timestamp: minsAgo(72),
      concern_level: "GREEN",
      risk_score: 0.14,
      top_feature: "sdnn",
      top_z_score: 0.35,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
  ],
  infant6: [
    {
      timestamp: minsAgo(115),
      concern_level: "GREEN",
      risk_score: 0.24,
      top_feature: "lf_hf_ratio",
      top_z_score: 0.7,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
    {
      timestamp: minsAgo(205),
      concern_level: "GREEN",
      risk_score: 0.19,
      top_feature: "rmssd",
      top_z_score: 0.05,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
  ],
  infant7: [
    {
      timestamp: minsAgo(64),
      concern_level: "GREEN",
      risk_score: 0.11,
      top_feature: "rmssd",
      top_z_score: -0.15,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
  ],
  infant8: [
    {
      timestamp: minsAgo(130),
      concern_level: "GREEN",
      risk_score: 0.29,
      top_feature: "pnn50",
      top_z_score: -0.75,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
    {
      timestamp: minsAgo(250),
      concern_level: "GREEN",
      risk_score: 0.22,
      top_feature: "sdnn",
      top_z_score: 0.1,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
  ],
  infant9: [
    {
      timestamp: minsAgo(99),
      concern_level: "GREEN",
      risk_score: 0.16,
      top_feature: "sdnn",
      top_z_score: 0.18,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
  ],
  infant10: [
    {
      timestamp: minsAgo(76),
      concern_level: "GREEN",
      risk_score: 0.27,
      top_feature: "rmssd",
      top_z_score: -0.65,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
    {
      timestamp: minsAgo(190),
      concern_level: "GREEN",
      risk_score: 0.21,
      top_feature: "pnn50",
      top_z_score: -0.3,
      signal_pattern: "normal_variation",
      brady_classification: null,
      agent_version: "multi_agent",
    },
  ],
};
